version: '3'

services:
  db:
    image: postgres:13
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django
    volumes:
      - postgres_data:/var/lib/postgresql/data
    read_only: false

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8200
    volumes:
      - .:/app:rw
    ports:
      - "8200:8200"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=store
      - DATABASE_USER=django_user
      - DATABASE_PASSWORD=django
      - DATABASE_HOST=db
      - DATABASE_PORT=5433
    read_only: false

volumes:
  postgres_data:
